config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'pages#home'
  #root to: 'blogs#index'
  
  get 'about-me', to: 'pages#about'
  #get 'home', to: 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'angular-items', to: 'portfolios#angular'
  get 'ror-items', to: 'portfolios#ror'

  put 'portfolios/sort', to: 'portfolios#sort'  # don't put this line below the following line else update action gets
                                                # called everytime instead of sort action. Now they are seperate.
  resources :portfolios, except: [:show]  # except option excludes the generation of 
                                          # natural routes for the passed value in array.
  resources :blogs do 
    member do
      get 'portfolio_status'   # learn more on: http://guides.rubyonrails.org/routing.html#adding-member-routes
    end
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'  # we overriden the general route for show action 

  # get 'pages/home'

  # get 'pages/contact'

  # get 'pages/about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :topics, only: [:index, :show]
  match '*unmatched' , to: redirect('/'), via: :all  # Used for redirection to root when no route matches

  # reference for above is:
  # 1. https://rollbar.com/blog/top-10-ruby-on-rails-errors/
  # 2. https://edgeguides.rubyonrails.org/routing.html#redirection
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :bigint(8)        not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#  status     :integer          default("draft")
#  topic_id   :bigint(8)
#

class Blog < ApplicationRecord
	enum status: { draft: 0, published: 1 }
	extend FriendlyId
	friendly_id :title, use: :slugged

	validates_presence_of :title, :body, :topic_id
	belongs_to :topic, optional: true

	def self.recent
		order('created_at DESC')
	end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :portfolio_status]
  before_action :set_sidebar_topics, except: [:create, :update, :destroy, :portfolio_status]

  # before_action makes the method (wriiten after it in the above line as syntax) to execute before the actions given 
  # in this controller class. only and except option are there to specifically include or exculdes some methods for this
  # action

  layout "blog"

  access all: [:show, :index], user: {except: [:destroy, :edit, :update, :new, :create, :portfolio_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    #@blogs = Blog.all.order('created_at DESC')  # This is done in order to maintain the order after update on UI. 
                                                # Else the updated record will move down the screen.
    #@blogs = Blog.all           # This one is the default scaffold generated one.
    @page_title = "Blog | My Portfolio Blog"  # Here we are overriding the value of @page_title variable present in the 
                                              # application_controller file. So, this value gets render when index page is accessed.
    if logged_in?(:site_admin)
      @blogs = Blog.recent.page(params[:page]).per(4)
    else
      @blogs = Blog.published.recent.page(params[:page]).per(4)                              
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    redirect_to blogs_path, notice: "You are not authorized to access this page" unless logged_in?(:site_admin) || @blog.published?
    @page_title = @blog.title
    @seo_keywords = @blog.title
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def portfolio_status
    if @blog.published?
      @blog.draft!
    elsif @blog.draft?
      @blog.published!
    end

    respond_to do |format|
      format.html { redirect_to blogs_url , notice: 'Blog status was successfully updated.' }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id]) #friendly is used to fetch the record based on the friendly url present
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id, :status)
    end

    def set_sidebar_topics
      @sidebar_topics = Topic.has_blogs
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
	class CodeRayify < Redcarpet::Render::HTML
		def block_code(code, language)
			CodeRay.scan(code, language).div
		end
	end

	def markdown(text)
		coderayified = CodeRayify.new(filter_html: true, hard_wrap: true) 

		options = {
			fenced_code_blocks: true,
			no_intra_emphasis: true,
			autolink: true,
			lax_html_blocks: true
		}

		markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
		markdown_to_html.render(text).html_safe
	end
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
	<h2 class="blog-post-title" ><%= link_to blog.title.to_s.titleize, blog %></h2>
	<% created_at = blog.created_at %>
	<% updated_at = blog.updated_at %>
	<% if created_at == updated_at %>
		<p class="blog-post-meta">Created <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago </p>
	<% else %>
	<p class="blog-post-meta">Created <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago </br>
	Updated <%= distance_of_time_in_words(blog.updated_at, Time.now) %> ago</p>
	<% end %>
	<p><%= markdown blog.body %></p>
	<% if logged_in?(:site_admin) %>
		<nav class="breadcrumb">
			<p class="">
				<%= link_to blog.status, portfolio_status_blog_path(blog) %> /
				<%= link_to 'Edit', edit_blog_path(blog) %> /
				<%= link_to 'Delete Blog', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
			</p>
		</nav>
	<% end %>
	<hr>
</div><!-- /.blog-post -->

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <!-- <div id="error_explanation">
      <h2><%#= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <%# blog.errors.full_messages.each do |message| %>
        <li><%#= message %></li>
      <%# end %>
      </ul>
    </div> -->
    <% blog.errors.full_messages.each do |msg| %>
      <%= alert_generator msg %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :topic_id %>
    <%= form.collection_select(:topic_id, Topic.all, :id, :title, 
                                {
                                  prompt: 'Please select the topic of this blog'
                                },
                                class: 'form-control',
                              ) 
    %>
  </div>

  <div class="form-group">
    <%= form.radio_button :status, 'draft' %>
    <%= form.label :status, 'Draft' %>

    <%= form.radio_button :status, 'published' %>
    <%= form.label :status, 'Published' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body, class: 'form-control h275' %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-md-8 blog-main">
	<h1>Editing Blog</h1>

	<%= render 'form', blog: @blog %>

	<%= link_to 'Show', @blog %> |
	<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/index.html.erb
<h1 class="col-md-12"> <%= "Hi, " + current_user.first_name %> <%= " - You are a " + current_user.role.to_s.capitalize if current_user.instance_of?(User) %></h1>
</br>
<div class="col-md-12">
	<%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %> / 
  <%= link_to 'Topics', topics_path %>
</div>
<h1 class="col-md-12">Blogs</h1>
<div class="col-md-8 blog-main">
  <%= paginate @blogs %>
  <%= render @blogs %>
  <%= paginate @blogs %>
</div>
<hr>

app/views/blogs/new.html.erb
<div class="col-md-8 blog-main">
	<h1>New Blog</h1>

	<%= render 'form', blog: @blog %>

	<%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-md-8 blog-main">
    <h2><%= @blog.title %></h2>
    <nav aria-label="breadcrumb row">
		  <ol class="breadcrumb">
		    <li class="breadcrumb-item"><%= link_to "Home", root_path %></li>
		    <li class="breadcrumb-item"><%= link_to @blog.topic.title, topic_path(@blog.topic) %></li>
		    <li class="breadcrumb-item active" aria-current="page"><%= @blog.title %></li>
		  </ol>
		</nav>
    <%= link_to 'Edit', edit_blog_path(@blog)  if logged_in?(:site_admin)  %> <%= '|'  if logged_in?(:site_admin) %>
    <%= link_to 'Back', blogs_path %></br></br>
    <%= markdown @blog.body %>  
</div>