config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'pages#home'
  #root to: 'blogs#index'
  
  get 'about-me', to: 'pages#about'
  #get 'home', to: 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'angular-items', to: 'portfolios#angular'
  get 'ror-items', to: 'portfolios#ror'

  put 'portfolios/sort', to: 'portfolios#sort'  # don't put this line below the following line else update action gets
                                                # called everytime instead of sort action. Now they are seperate.
  resources :portfolios, except: [:show]  # except option excludes the generation of 
                                          # natural routes for the passed value in array.
  resources :blogs do 
    member do
      get 'portfolio_status'   # learn more on: http://guides.rubyonrails.org/routing.html#adding-member-routes
    end
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'  # we overriden the general route for show action 

  # get 'pages/home'

  # get 'pages/contact'

  # get 'pages/about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :topics, only: [:index, :show]
  match '*unmatched' , to: redirect('/'), via: :all  # Used for redirection to root when no route matches

  # reference for above is:
  # 1. https://rollbar.com/blog/top-10-ruby-on-rails-errors/
  # 2. https://edgeguides.rubyonrails.org/routing.html#redirection
end

app/models/portfolio.rb
# == Schema Information
#
# Table name: portfolios
#
#  id          :bigint(8)        not null, primary key
#  title       :string
#  subtitle    :string
#  body        :text
#  main_image  :text
#  thumb_image :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  position    :integer
#

class Portfolio < ApplicationRecord
	has_many :technologies, dependent: :destroy   

	# dependent: :destroy allows us to delete the associated records(techonologies), else the error would pop up like:
	# ActiveRecord::InvalidForeignKey (PG::ForeignKeyViolation: ERROR:  update or delete on table "portfolios" violates 
	# foreign key constraint "fk_rails_cc5ab4a1c3" on table "technologies"
	# DETAIL:  Key (id)=(11) is still referenced from table "technologies"

	accepts_nested_attributes_for :technologies,
								  allow_destroy: true,
								  reject_if: lambda { |attr| attr['name'].blank? }

	validates_presence_of :title, :body

	mount_uploader :thumb_image, PortfolioUploader
	mount_uploader :main_image, PortfolioUploader

	scope :ruby_on_rails_items, -> { where(subtitle: "Ruby On Rails") }
	scope :by_position, -> { order('position ASC') }
	
	def self.angular_items
		where(subtitle: "Angular")
	end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	layout "portfolio"
	
	access all: [:show, :index, :angular, :ror], user: {except: [:destroy, :edit, :update, :new, :create, :sort]}, site_admin: :all


	def index
		@portfolios_items = Portfolio.by_position
		#@portfolios_items = Portfolio.all.order("created_at DESC")
		#@portfolios_items = Portfolio.where(subtitle: "Ruby On Rails")
		#@portfolios_items = Portfolio.where(subtitle: "Angular")
		#@portfolios_items = Portfolio.all
	end

	def sort
		params[:order].each do |key, value|
			Portfolio.find(value[:id]).update!(position: value[:position]) rescue ''
		end

		render body: nil
	end

	def angular
		@angular_items = Portfolio.angular_items
	end

	def ror
		@ror_items = Portfolio.ruby_on_rails_items	
	end

	def new
		@portfolio_item = Portfolio.new
		1.times { @portfolio_item.technologies.build }  #This is commented to make the coocon working
	end

	def create
    	@portfolio_item = Portfolio.new(portfolios_params)
    
	    respond_to do |format|
	      if @portfolio_item.save
	        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
	      else
	        format.html { render :new }
	      end
	    end
	end

	def edit
		@portfolio_item = Portfolio.find(params[:id])
		#1.times { @portfolio_item.technologies.build }
	end

	def update
	  @portfolio_item = Portfolio.find(params[:id])

	  respond_to do |format|
	    if @portfolio_item.update(portfolios_params)
	      format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
	      
	    else
	      format.html { render :edit }
	    end
	  end
  	end

  	def show
  		@portfolio_item = Portfolio.find(params[:id])
  	end
	
  	def destroy
  		@portfolio_item = Portfolio.find(params[:id])

  		@portfolio_item.destroy
  		# respond_to do |format|
  		# 	format.html { redirect_to portfolios_path }
  		# end
  		redirect_to portfolios_path
  	end

  	private

  	def portfolios_params
  		params.require(:portfolio).permit(:id, :title, 
  										  :subtitle, 
  										  :body,
  										  :main_image,
  										  :thumb_image, 
    									  technologies_attributes: 
    									  [:name, :id, :_destroy])
  	end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
	def image_generator(height:, width:)
		"http://placehold.it/#{height}x#{width}"
		#"rafale.jpg"
	end

	def portfolio_img img, type
		if img.model.thumb_image? || img.model.main_image?
			img
		elsif type == 'thumb'
			image_generator(height: '350', width: '200')
		elsif type == 'main'
			image_generator(height: '600', width: '400')
		end
	end
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio_item, local: true) do |form| %>
  <% portfolio_item.errors.full_messages.each do |msg| %>
    <%= alert_generator msg %>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control", required: true %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: "form-control", required: true %>
      </div>
      <div class="form-group">
        <%= form.file_field :main_image %>
      </div>
      <div class="form-group">
         <%= form.file_field :thumb_image %>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: "form-control", required: true, rows: 10 %>
      </div>
    </div>
  </div>
    
   <!--  <div class="col-md-12">
      <h3>Technologies :</h3>
        <div>
          <%#= form.fields_for :technologies do |technology_form| %>
            <div class="form-group">
              <%#= technology_form.label :name %>
              <%#= technology_form.text_field :name, class: "form-control", required: true %> 
            </div>
          <%# end %>
        </div> 
    </div>
 -->

    <%#= '<h3>Technologies :</h3>'.html_safe if portfolio_item.technologies.count != 0 && params[:action] == "edit" %>
    <h3>Technologies :</h3>
    <div>
      <%= form.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %> 
      <% end %>
    </div>
    <div>
      <%= link_to_add_association 'Add Technology', form, :technologies, class: 'btn btn-success' %>
    </div>

    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6 form-group">
        <%= form.submit "Save Portfolio Item", class: "form-control btn btn-primary" %>
      </div>
      <div class="col-md-3"></div> 
    </div>
    
<% end %>

app/views/portfolios/_portfolios_item.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow-sm" data-id="<%= portfolios_item.id %>">
    <%= image_tag portfolio_img(portfolios_item.thumb_image, 'thumb'), height: 200, class: "card-img-top" %>
    <div class="card-body">
      <p class="card-text">
      	<span><%= link_to portfolios_item.title, portfolio_show_path(portfolios_item) %></span>
      </p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
		  		<%= link_to "Edit", edit_portfolio_path(portfolios_item), class: 'btn btn-sm btn-outline-secondary' if logged_in?(:site_admin) %>
		  		<%= link_to 'Delete', portfolio_path(portfolios_item.id), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-secondary' if logged_in?(:site_admin) %>
        </div>
        <small class="text-muted">9 mins</small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
	<%= f.label :name %> 
	<%= f.text_field :name, class: 'form-control', required: true %>
	<%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1>Portfolio Items</h1>
<%= link_to "New Portfolio", new_portfolio_path if logged_in?(:site_admin) %>
<!-- <a href="/portfolios/new">New port</a> -->
<% @angular_items.each do |portfolios_item| %>
	<p><%= link_to "Show " + portfolios_item.title, portfolio_show_path(portfolios_item) %></p>
	<p><%= portfolios_item.subtitle %></p>
	<p><%= portfolios_item.body %></p>
	<p><%= image_tag portfolios_item.thumb_image unless portfolios_item.thumb_image.nil? %></p>
	<p><%#= link_to "Edit", edit_portfolio_path(portfolios_item.id) %></p>
	<p><%= link_to "Edit", edit_portfolio_path(portfolios_item) if logged_in?(:site_admin) %></p>
	<p><%= link_to 'Delete Portfolio', portfolio_path(portfolios_item.id), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></p>
	<%#= portfolios_item.inspect %>
	<div> ----------------------------------------------------------------------------------------------------- </div>
<% end %>	

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
	<div class="row">
		<div class="col-md-6"><h2>Edit the Portfolio item</h2></div>
		<div class="col-md-4"></div>
		<div class="col-md-2"><a href="/portfolios">View all portfolios</a></div>
	</div>
	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
	<div class="container">
		<div class="col-md-12" style="margin-bottom: 20px;padding-left: 0px;">
				<%= link_to '<i class="fa fa-plus"></i>&nbsp; New Portfolio'.html_safe , new_portfolio_path, class: 'btn btn-outline-success' if logged_in?(:site_admin)  %>
		</div>
		<div class="row <%= "sortable" if logged_in?(:site_admin) %>">
			<%= render partial: 'portfolios_item', collection: @portfolios_items %>
		</div>
	</div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
	<div class="row">
		<div class="col-md-6"><h2>Create a new Portfolio item</h2></div>
		<div class="col-md-4"></div>
		<div class="col-md-2"><a href="/portfolios">View all portfolios</a></div>
	</div>
	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/ror.html.erb
<h1>Portfolio Items</h1>
<%= link_to "New Portfolio", new_portfolio_path if logged_in?(:site_admin) %>
<!-- <a href="/portfolios/new">New port</a> -->
<% @ror_items.each do |portfolios_item| %>
	<p><%= link_to "Show " + portfolios_item.title, portfolio_show_path(portfolios_item) %></p>
	<p><%= portfolios_item.subtitle %></p>
	<p><%= portfolios_item.body %></p>
	<p><%= image_tag portfolios_item.thumb_image unless portfolios_item.thumb_image.nil? %></p>
	<p><%#= link_to "Edit", edit_portfolio_path(portfolios_item.id) %></p>
	<p><%= link_to "Edit", edit_portfolio_path(portfolios_item) if logged_in?(:site_admin) %></p>
	<p><%= link_to 'Delete Portfolio', portfolio_path(portfolios_item.id), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %></p>
	<%#= portfolios_item.inspect %>
	<div> ----------------------------------------------------------------------------------------------------- </div>
<% end %>	

app/views/portfolios/show.html.erb
<div class="container mt30">
	<div class="row">
		<div class="col-md-7">
			<%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %>
		</div>
		<div class="col-md-5">			
			<p><h3><%= @portfolio_item.title %></h3></p>
			<em><%= @portfolio_item.subtitle %></em>
			<p><%= @portfolio_item.body %></p>

			<% if @portfolio_item.technologies.count != 0 %>
				<h2>Technologies Used: </h2>
				<% @portfolio_item.technologies.each do |t| %>
					<p><%= t.name %></p>
				<% end %>
			<% end %>
			<%= link_to 'Edit Item', edit_portfolio_path(@portfolio_item), class: 'btn btn-warning' if logged_in?(:site_admin)%>
		</div>
	</div>
</div>