config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'pages#home'
  #root to: 'blogs#index'
  
  get 'about-me', to: 'pages#about'
  #get 'home', to: 'pages#home'
  get 'contact', to: 'pages#contact'
  get 'angular-items', to: 'portfolios#angular'
  get 'ror-items', to: 'portfolios#ror'

  put 'portfolios/sort', to: 'portfolios#sort'  # don't put this line below the following line else update action gets
                                                # called everytime instead of sort action. Now they are seperate.
  resources :portfolios, except: [:show]  # except option excludes the generation of 
                                          # natural routes for the passed value in array.
  resources :blogs do 
    member do
      get 'portfolio_status'   # learn more on: http://guides.rubyonrails.org/routing.html#adding-member-routes
    end
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'  # we overriden the general route for show action 

  # get 'pages/home'

  # get 'pages/contact'

  # get 'pages/about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :topics, only: [:index, :show]
  match '*unmatched' , to: redirect('/'), via: :all  # Used for redirection to root when no route matches

  # reference for above is:
  # 1. https://rollbar.com/blog/top-10-ruby-on-rails-errors/
  # 2. https://edgeguides.rubyonrails.org/routing.html#redirection
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
	<%= js add_gritter(flash[:alert], title: "Pankaj's Portfolio's items", time: 2000) %>
<% elsif flash[:error] %>
	<%= js add_gritter(flash[:error], title: "Pankaj's Portfolio's items", time: 2000) %>
<% elsif flash[:notice] %>
	<%= js add_gritter(flash[:notice], title: "Pankaj's Portfolio's items", time: 2000) %>
<% end %>

app/views/shared/_application_footer.html.erb
 <footer class="mastfoot mt-auto">
  <div class="inner app-footer">
   <!--  <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p> -->
   	<%= copyright_generator %>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
   <div class="inner">
      <h3 class="masthead-brand">Pankaj Kumar Singh</h3>
      <nav class="nav nav-masthead justify-content-center app-nav">
        <%= nav_helper('nav-link','span') %>
        <%= login_helper('nav-link') %>
        <!-- <a href=<%#= "/abc.log" %> class="nav-link" target="self" download>Log file</a> -->
      </nav>
   </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
	<%= copyright_generator %> </br></br>
	<p>
	<a href="#">Back to top</a>
	</p>
</footer>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
	<div class="container">
		<%= link_to "Pankaj Kumar Singh", root_path, class: "navbar-brand white-color" %>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="border-color: white;">
			<span class="navbar-toggler-icon"></span>
		</button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    	<ul class="navbar-nav">
    		<%= nav_helper('p-2 text-muted nav-link white-color','li') %>
        	<%= login_helper('p-2 text-muted nav-link white-color') %>
    	</ul>
    </div>
	</div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar mt20">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">This blog is about creating a <em>blog</em> to understand the working of rails workflow using the blog concept and various operations on them</p>
  </div>

  <div class="p-3">
    <% @sidebar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled row li-pd10">
      <li><a href="https://twitter.com/login?lang=en" target="_blank"><%= fa_icon "twitter" %></a></li>
      <li><a href="https://github.com/pankajks16" target="_blank"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.facebook.com/" target="_blank"><%= fa_icon "facebook-square" %></a></li>
      <li><a href="https://www.instagram.com/accounts/login/?hl=en" target="_blank"><%= fa_icon "instagram" %></a></li>
      <li><a href="https://web.whatsapp.com/" target="_blank"><%= fa_icon "whatsapp" %></a></li>
      <li><a href="https://in.linkedin.com/" target="_blank"><%= fa_icon "linkedin-square" %></a></li>
    </ol>
  </div>
</aside><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
 <div class="<%= location rescue '' %>">
      <div><%= link_to "Home", root_path %></div>
      <div><%= link_to "About", about_me_path %></div>
      <div><%= link_to "Contact", contact_path %></div>
      <div><%= link_to "Portfolio", portfolios_path %></div>
 </div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="/portfolios">View all portfolios</a> /
      <a href="#">Back to top</a>
    </p>
      <%= copyright_generator %>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center" style="padding-bottom: 0px;">
   <div class="container">
     <h1 class="jumbotron-heading">My Portfolio</h1>
     <p class="lead text-muted">I'm a ruby developer based in garden city called Bengaluru .... and with an essence of love it is also called as Namma Bengaluru</p>
     <p>
       <a href="/about-me" class="btn btn-primary my-2">Find more about me</a>
       <a href="/blogs" class="btn btn-secondary my-2">My Blog</a>
     </p>
   </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">I'm a ruby developer based in garden city called Bengaluru .... and with an essence of love it is also called as Namma Bengaluru</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper('text-white','li') %>
          <li><%= login_helper('text-white') %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container d-flex justify-content-between">
    <span class="navbar-brand d-flex align-items-center">
      <a href="/" style="color: white;text-decoration: none"><strong>Pankaj Kumar Singh</strong></a>
    </span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>